baseURL = 'https://sihyeong671.github.io/'
languageCode = 'en-us'
title = 'Portfolio'
theme = "hugo-resume"
profileImage = ""
showContact = true

# PygmentsCodeFences = true
# PygmentsCodeFencesGuessSyntax = true
# PygmentsStyle = "monokai"
enableGitInfo = false


[params]
address = "Busan, KR"
email = "bshlab671@naver.com"
favicon = "/favicon.ico"
firstName = "Sihyeong"
lastName = "Park"
# phone = ""
profileImage = "images/my_img.jpg"
# showContact = true
showSocializations = true
sections = ["skills", "project", "competitions", "contributions"]



[[params.handles]]
link = "https://github.com/sihyeong671/"
name = "GitHub"

[[params.handles]]
link = "https://www.linkedin.com/in/%EC%8B%9C%ED%98%95-%EB%B0%95-370207272/"
name = "LinkedIn"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"